const ProductsArray = [
  {
    id: 1,
    name: "Susuwatari Trouble",
    description: "These little dust mites are always up to something",
    price: "25.00",
    image: "Images/StudioGProduct1.jpeg",
  },
  {
    id: 2,
    name: "Howl & Sophie",
    description: "A love like no other",
    price: "50.00",
    image: "Images/StudioGProduct2.jpeg",
  },
  {
    id: 3,
    name: "In the Water!",
    description: "Ponyo's on an adventure at sea",
    price: "35.00",
    image: "Images/SudioGProduct3.jpeg",
  },
  {
    id: 4,
    name: "Peace in the Sky",
    description: "Haku taking Chihiro for a ride",
    price: "45.00",
    image: "Images/StudioGProduct4.jpeg",
  },
  {
    id: 5,
    name: "Soul Cake",
    description: "Well earned after a day at the bath house",
    price: "20.00",
    image: "Images/StudioGProduct5.jpeg",
  },
  {
    id: 6,
    name: "He Says he's Good Luck",
    description: "Not all black cats are bad",
    price: "15.00",
    image: "Images/SudioGProduct6.jpeg",
  },
  {
    id: 7,
    name: "Better Days",
    description: "We hope Howl gets better soon",
    price: "30.00",
    image: "Images/StudioGProduct7.jpeg",
  },
  {
    id: 8,
    name: "The Kodama",
    description: "Don't worry, they're just looking out for the forest",
    price: "15.00",
    image: "Images/StudioGProduct8.jpeg",
  },
  {
    id: 9,
    name: "Howl's Trouble",
    description: "Sophie hopes for Howl's return amidst the chaos",
    price: "35.00",
    image: "Images/StudioGProduct9.jpeg",
  },
  {
    id: 10,
    name: "The Light Within",
    description: "Howl just needed to look within",
    price: "40.00",
    image: "Images/StudioGProduct10.jpeg",
  },
  {
    id: 11,
    name: "Safe Travels, Friend",
    description: "Woah! I wonder who's in there",
    price: "45.00",
    image: "Images/StudioGProduct11.jpeg",
  },
  {
    id: 12,
    name: "One With the Pack",
    description: "A true princess",
    price: "15.00",
    image: "Images/StudioGProduct12.jpeg",
  },
];

export default ProductsArray;
